Kernel360/KFE3-e2e-Chwee-up-hajah

- apps/docs/machines/machines-example.ts
- apps/docs/package.json
- pnpm-lock.yaml
xstate를 설치하고 해당 예제 파일을 생성했습니다.  
추후 차트화가 필요하다면 추가 라이브러리 설치가 필요합니다.
정상 작동을 확인하려면 state를 사용해야해서 현재 확인까지는 못한 상태입니다.
> chore: xstate 설치 및 예제 파일 생성

- apps/docs/app/globals.css
- apps/web/app/globals.css
- apps/web/app/page.tsx
- packages/ui/src/design-system/base-components/Badge/Badge.tsx
수정한 내용이나 추가한 기능에 대해 자세히 설명해 주세요.
globals.css 컴파일된 css import 대신 theme.css 파일 import
전
```css
@import 'tailwindcss';
@import '@repo/ui/styles';
```
후
```css
@import 'tailwindcss';
@import '@repo/ui/theme';
```
주요 변경 사항을 요약해 주세요.
수정된 화면 또는 기능을 시연할 수 있는 스크린샷을 첨부해 주세요.
추가적으로 전달하고 싶은 내용이나 특별한 요구 사항이 있으면 작성해 주세요.
> Fix/css import structure #29

- apps/web/app/(main)/auction/my-listings/page.tsx
- apps/web/app/(main)/auction/participating/page.tsx
- apps/web/app/(main)/auction/won-items/page.tsx
- apps/web/app/(main)/profile/charge-history/page.tsx
- apps/web/app/(main)/profile/page.tsx
- apps/web/entities/auction/ui/AuctionCard.tsx
- apps/web/pages/charge-history-page/index.ts
- apps/web/pages/charge-history-page/ui/index.tsx
- apps/web/pages/my-listings-page/index.ts
- apps/web/pages/my-listings-page/ui/index.tsx
- apps/web/pages/profile-page/index.ts
- apps/web/pages/profile-page/ui/index.tsx
- apps/web/widgets/auction-listings/index.ts
- apps/web/widgets/auction-listings/ui/AuctionListings.tsx
- apps/web/widgets/profile/index.ts
- apps/web/widgets/profile/types/index.ts
- apps/web/widgets/profile/ui/ChargeHistoryList.tsx
- apps/web/widgets/profile/ui/Navigation.tsx
- apps/web/widgets/profile/ui/UserProfileCard.tsx
- 프로필 페이지
- 충전 내역 페이지
- 참여한 경매 물품 내역 페이지
(폴더 구조)
```jsx
src/
├── app/
├── pages/
│	 └── charge-history-page/                # 내 충전내역 페이지            
│       │   ├── ui/
│       │   │   └── index.tsx              
│       │   └── index.ts
│  └── my-listings-page/                   # 내가 등록한 경매 물품 페이지           
│       │   ├── ui/
│       │   │   └── index.tsx              
│       │   └── index.ts
│  └── participatings-page/                # 내가 참여한 경매 물품 페이지           
│       │   ├── ui/
│       │   │   └── index.tsx              
│       │   └── index.ts
│  └── won-items-page/                     # 낙찰받은 물품 페이지           
│       │   ├── ui/
│       │   │   └── index.tsx              
│       │   └── index.ts
│	 └── profile-page/                       # 내 프로필 페이지              
│       │ …
```
> Feat/profile #4

- apps/web/app/api/auth/check-duplicate/route.ts
- apps/web/app/api/auth/me/route.ts
- apps/web/app/api/auth/webhook/route.ts
- apps/web/app/server.ts
- apps/web/app/session.ts
- apps/web/features/authentication/api/login.ts
- apps/web/features/authentication/api/logout.ts
- client.ts, server.ts 둘다 함수 이름 createclient
- server.ts는 SSR을 붙여 사용
> refactor/server.ts 함수 이름 변경

- apps/web/features/chat-room/model/sendMessage.ts
- apps/web/features/chat-room/ui/ChatMessages.tsx
- apps/web/hooks/chat/useMessageSubscription.ts
- apps/web/tsconfig.json
- app route 방식으로 api 변경
- realtime 구독 오류 
- read 읽음 기능 구현
https://www.notion.so/E2E-1f4a3f519ab880d3ba2ffea5a92777e6?p=223a3f519ab880b8b4d9dd374d704eb3&pm=s
노션글에 업로드하였습니다.
> bug: 채팅 페이지- 구독 오류  (#92)

- apps/web/app/(main)/profile/page.tsx
- apps/web/app/(main)/profile/update/page.tsx
- apps/web/widgets/footer/ui/Footer.tsx
> feat: footer href 페이지 연결

- apps/web/types/modal/index.ts
- apps/web/widgets/modal/ui/NotificationModal.tsx
모달 컴포넌트에 정의한 타입 types 폴더로 분리하였습니다.
> refactor: 모달 컴포넌트 타입 정의 분리(#120)

- apps/web/features/profile/styles/profileAvatarUpload.styles.ts
- apps/web/features/profile/ui/ProfileAvatarUpload.tsx
- apps/web/widgets/footer/styles/footer.styles.ts
- apps/web/widgets/footer/ui/Footer.tsx
- apps/web/widgets/header/styles/header.styles.ts
- apps/web/widgets/header/ui/Header.tsx
- apps/web/widgets/modal/styles/locationModal.styles.ts
- apps/web/widgets/modal/styles/locationPermissionModal.ts
- apps/web/widgets/modal/styles/notificationModal.styles.ts
- apps/web/widgets/modal/ui/LocationModal.tsx
- apps/web/widgets/modal/ui/LocationPermissionModal.tsx
- apps/web/widgets/modal/ui/NotificationModal.tsx
- apps/web/widgets/profile/styles/chargeHistory.styles.ts
- apps/web/widgets/profile/styles/navigation.styles.ts
- apps/web/widgets/profile/styles/profileForm.styles.ts
- apps/web/widgets/profile/styles/useProfileCard.styles.ts
- apps/web/widgets/profile/ui/ChargeHistoryList.tsx
- apps/web/widgets/profile/ui/Navigation.tsx
- apps/web/widgets/profile/ui/ProfileForm.tsx
- apps/web/widgets/profile/ui/UserProfileCard.tsx
> Refactor/separate component styles #119

- apps/web/app/(main)/main/page.tsx
- apps/web/app/(main)/main/styles/main.styles.ts
- apps/web/features/product-list/ui/ProductCard.tsx
- apps/web/features/product-list/ui/ProductList.tsx
- apps/web/features/product-list/ui/styles/product-card.styles.ts
- apps/web/features/product-list/ui/styles/product-list.styles.ts
- apps/web/widgets/image-banner/ui/ImageBanner.tsx
- apps/web/widgets/image-banner/ui/styles/image-banner.styles.ts
- apps/web/widgets/product-section-header/ui/SectionHeader.tsx
- apps/web/widgets/product-section-header/ui/styles/section-header.styles.ts
- apps/web/widgets/product-section/ui/ProductSection.tsx
- apps/web/widgets/product-section/ui/styles/product-section.styles.ts
main 관련 컴포넌트들의 css 상수화
ProductCard.tsx
ProductList.tsx
ImageBanner.tsx
section-header
관련 컴포넌트들 상수화 후 폴더 정리
> refactor: main page 관련 컴포- css 상수화 (#147)

- apps/web/app/(main)/main/page.tsx
SectionHeader 의 더보기 버튼 auction-list 페이지 경로 설정
)
> feat: SectionHeader -  더보기 rotuer.push 추가 (#150)

- apps/web/app/api/README.md
- apps/web/app/providers.tsx
- apps/web/features/authentication/model/types.ts
- apps/web/hooks/mutations/useCheckDuplicateMutation.ts
- apps/web/hooks/mutations/useLoginMutation.ts
- apps/web/hooks/mutations/useSignupMutation.ts
- apps/web/hooks/queries/useRestoreSessionQuery.ts
- apps/web/hooks/useLogin.ts
- apps/web/hooks/useSignup.ts
- apps/web/stores/auth.ts
> refactor: Login, Signup TanStack Query로 변경

- apps/web/app/api/auction/bid/route.ts
- apps/web/app/api/auction/bidder-name/route.ts
- apps/web/app/api/auction/detail/[auctionId]/route.ts
- apps/web/app/api/auction/list/route.ts
- apps/web/features/auction-add/model/useAuctionAddForm.ts
- apps/web/features/auction-detail/model/useAuctionBidState.ts
- apps/web/features/auction-detail/model/useSendBid.ts
- apps/web/features/auction/ui/AuctionCard.tsx
- apps/web/features/auction/ui/styles/AuctionCard.styles.ts
- apps/web/shared/api/server/auction/fetchBidderName.ts
- apps/web/shared/hooks/useRealTimeBid.ts
- apps/web/shared/types/auction/index.ts
- apps/web/widgets/auction-listings/ui/AuctionListings.tsx
- apps/web/widgets/auction-listings/ui/styles/AuctionListings.styles.ts
경매 관련 페이지의 미비된 api 분리 및 폴더 구조 변경에 따른 import 주소 변경이 안된 부분 수정
경매 관련 페이지의 미비된 api 분리
폴더 구조 변경에 따른 import 주소 변경이 안된 부분 수정
> [refactor]: 경매 관련 페이지 폴더 구조 변경에 따른 url 변경 안된 부분 수정 및 api 추가 분리

- apps/web/app/(main)/auction/my-listings/page.tsx
- apps/web/app/api/auction/my-listings/ended/route.ts
- apps/web/app/api/auction/my-listings/in-progress/route.ts
- apps/web/app/api/auction/my-participated/route.ts
- apps/web/app/api/auction/my-won-auctions/route.ts
- apps/web/shared/api/client/auction/useMyListings.ts
- apps/web/widgets/my-listings/ui/MyListings.tsx
내 판매 내역 페이지
내가 경매에 올린 판매 물품을 볼 수 있는 페이지입니다. 
- select 옵션으로 판매중 | 종료된 판매 내역을 볼 수 있습니다.
> Feat/my listings #156

- apps/web/features/profile/ui/ProfileAvatarUpload.tsx
- apps/web/widgets/profile/ui/ProfileForm.tsx
- PR #110 에서 프로필 업데이트 로직을 수정하고 머지 완료했으나 현재 dev 브랜치에서 수정 전 코드로 되돌아가 있음
- 유실된 코드 다시 복구
> fix: 프로필 업데이트 로직 재적용(유실된 코드 복구)

- apps/web/app/(auth)/dashboard/page.tsx
- apps/web/app/(auth)/login/page.tsx
- apps/web/shared/hooks/useLogin.ts
- apps/web/shared/stores/auth.ts
- useAuthStore userId null 버그 해결
- TanStack Query에서 onSuccess 시 useAuthStore userId를 저장하는 형식으로 변경
> fix: useId 상태 추가

- package.json
- pnpm-lock.yaml
CD 에러를 고치기위해 루트 package.json에 cypress를 설치했습니다.
> test: 루트 패키지에 cypress 설치

- .github/workflows/ci.yml
- .github/workflows/cypress.yml
Trigger sync in fork repo
ci -> cypress 통과되면 트리거 실행되도록 변경
> test: trigger 를 cypress에 추가

- apps/web/app/(test)/admin/events/page.tsx
- apps/web/app/(test)/admin/hot_deals/page.tsx
- apps/web/app/api/auth/signup/route.ts
- apps/web/app/api/hot-deals/route.ts
- apps/web/middleware.ts
- apps/web/next-env.d.ts
- apps/web/shared/lib/validators/hot-deal.ts
- apps/web/widgets/modal/index.ts
- packages/ui/src/design-system/base-components/Input/Input.tsx
closes #225 
- 핫딜 관리 기능 추가 및 개선 
- 핫딜 관리 페이지에 핫딜을 활성화/비활성화하고 상태를 확인할 수 있는 기능을 추가
- supabase DB Table 생성 및  SQL문으로 cron 처리
- **핫딜 활성화/비활성화**: 사용자가 버튼 클릭으로 특정 핫딜의 `is_active` 상태를 변경할 수 있도록 `PATCH` API와 클라이언트 로직 구현
- **핫딜 상태 표시**: API에서 각 핫딜의 시작/종료 시간 및 활성화 여부를 기반으로 `진행중`, `대기중`, `종료됨`, `비활성화` 상태 표시
```SQL
CREATE OR REPLACE FUNCTION apply_hot_deal_price_drop()
RETURNS void AS $$
BEGIN
UPDATE hot_deals
SET
current_price = greatest(min_price, current_price - price_drop_amount),
last_price_drop_at = now()
WHERE
(end_time IS NULL OR now() < end_time)
AND (start_time IS NULL OR now() >= start_time)
AND now() >= COALESCE(last_price_drop_at, start_time) + (price_drop_interval_minutes * interval '1 minute');
END;
$$ LANGUAGE plpgsql;
SELECT cron.schedule(
'hotdeal-price-drop',
'* * * * *',
'SELECT …
```
> feat: 핫딜 관리자 페이지 구현

- apps/web/app/api/auction/my-participated/route.ts
- 내 참여 경매 중 같은 경매일 때 내 최고 입찰가만 남기게 변경
> refactor: 참여 중 경매 중 같은 경매면 내 최고 입찰가만 남기기

- apps/web/app/api/point/deduct-test/route.ts
- apps/web/widgets/profile/ui/PointsHistoryList.tsx
- apps/web/widgets/profile/ui/PointsTestButton.tsx
- apps/web/widgets/profile/ui/UserProfileCard.tsx
> Refactor/point #318

- apps/web/shared/api/client/authentication/useLoginMutation.ts
- apps/web/shared/hooks/useSignup.ts
- apps/web/shared/lib/validators/auth.ts
- apps/web/widgets/authentication/AddressInputSection.tsx
- apps/web/widgets/authentication/SignupFormComponent.tsx
closes #314 
- Cron job를 이용해 인증되지 않은 이메일 삭제(user, auth.users)
- 주소 Input에 Click Event 생성
- Validation 추가(비밀번호, 닉네임 최대 차리)
- 필수 사항 두 개를 모두 체크해야 회원가입이 될 수 있도록 수정
- ssr cookie refresh(회원가입 버튼 안눌러지는 버그 수정, router.refresh)
``` SQL
DROP FUNCTION IF EXISTS cleanup_unverified_users_safe();
CREATE OR REPLACE FUNCTION cleanup_unverified_users_safe()
-- email 컬럼의 반환 타입을 text에서 character varying으로 수정
RETURNS TABLE(deleted_user_id UUID, email character varying) AS $$
BEGIN
RETURN QUERY
WITH users_to_delete AS (
SELECT au.id, au.email
FROM auth.users au
WHERE au.last_sign_in_at IS NULL
AND au.email_confirmed_at IS NULL
AND au.created_at < NOW() - INTERVAL '10 minutes'
),
delete_public AS (
DELETE FROM public.user
WHERE user_id IN (SELECT id FROM users_to_delete)
RETURNING user_id
),
delete_auth AS ( …
```
> fix/회원가입 버그 수정

- apps/web/app/(main)/auction/my-listings/page.tsx
- apps/web/app/(main)/profile/page.tsx
- apps/web/app/(no-footer)/layout.tsx
- apps/web/app/api/auction/list/route.ts
- apps/web/app/api/auction/my-listings/closed/route.ts
- apps/web/app/api/auction/my-listings/in-progress/route.ts
- apps/web/app/api/auction/my-participated/route.ts
- apps/web/app/api/auction/my-won-auctions/route.ts
- apps/web/shared/api/client/profile/useUpdateProfile.ts
- apps/web/widgets/authentication/LogoutButton.tsx
- apps/web/widgets/profile/ui/PointsTestButton.tsx
- 프로필 경매 관련 내역 변경된 status 로직 적용
- 프로필 toast 추가 (프로필 업데이트, 포인트 적립/차감, 로그아웃)
- 로그아웃 시 "로그아웃 하시겠습니까?" confirm 창 추가 
toast 추가
> [Fix] 프로필 auction status 수정 및 toast 적용 

- apps/web/app/(auth)/signup/page.tsx
- apps/web/shared/lib/notification/pushService.ts
- apps/web/widgets/authentication/styles/index.ts
- apps/web/widgets/header/ui/Header.tsx
- apps/web/widgets/modal/ui/NotificationModal.tsx
- 핫딜 푸시 알림에 한 유저가 구독한 모든 기기에 알림을 보냅니다. 
- 회원가입 페이지 padding 제거 다른 페이지와 너비 맞춤
- 헤더 조건문 경로 상세 시정
> [fix] 핫딜 멀티 디바이스 알림 적용 

- apps/web/app/api/chat/confirm-completion/route.ts
- apps/web/app/api/chat/message-send/route.ts
- apps/web/app/api/chat/reject-completion/route.ts
- apps/web/app/api/chat/request-completion/route.ts
- apps/web/widgets/modal/ui/NotificationModalItem.tsx
chat message & 거래 완료 동의  push 기능 오류 해결
pushService.ts 사용하기
> [Fix] chat에 push 오류   #290

- apps/web/app/(main)/hotdeal/[hotdealId]/detail/page.tsx
- apps/web/app/(main)/layout.tsx
- apps/web/widgets/scroll-button/ScrollButton.styles.ts
- packages/ui/src/design-system/base-components/Avatar/Avatar.tsx
- 프로필 아바타 이미지 최적화를 위해 next/image를 사용하면서 기본 이미지 svg 파일이 렌더링 되지 않는 현상
- next/image의 unoptimize={true} 속성을 통해 svg 파일인 경우 최적화를 건너뜀.
- 전체적인 css 변경
> Fix/svg unoptimize #391
